### ISSUE TITLE
Suggestion: Adjust the order of steps in README for clarity

### ISSUE THREAD

**Issue by ouerwt** [wrh14/deep_unlearning#2]
In the current README, the instructions for *"Evaluate Deep Unlearning on EDU-RELAT"* are listed before *"Reproducing the results of unlearning methods in the paper"*. However, the evaluation step depends on the output files (`relationships_correct.pt` and `biographies_correct.pt`) generated by running the unlearning methods.  

To avoid confusion, it would be clearer to switch the order of these two sections so that users first run the unlearning methods and then proceed with the evaluation.  

This is based on my understanding of the instructions. If I misunderstood something, please feel free to correct me.

**Comment by wrh14** [comment]
Hi, 

Thanks for your consideration! We introduced the evaluation block first because the evaluation would be generally used for all unlearning methods, including both the methods in our paper and the potential future method. However, we agree that the script of running the evaluation code needs the output files first (from any unlearning method). To avoid confusion, we add a folder `example_for_evaluation`, which includes an example of output files, so one can run the script 
```
python calculate_recall_and_acc.py --unlearn_data_id 1 --input_dir example_for_evaluation
```
to understand what format of output files is needed to evaluate with their own methods.

Please let us know if there any other confusion!

**Comment by ouerwt** [comment]
> Hi,
> 
> Thanks for your consideration! We introduced the evaluation block first because the evaluation would be generally used for all unlearning methods, including both the methods in our paper and the potential future method. However, we agree that the script of running the evaluation code needs the output files first (from any unlearning method). To avoid confusion, we add a folder `example_for_evaluation`, which includes an example of output files, so one can run the script
> 
> ```
> python calculate_recall_and_acc.py --unlearn_data_id 1 --input_dir example_for_evaluation
> ```
> 
> to understand what format of output files is needed to evaluate with their own methods.
> 
> Please let us know if there any other confusion!

Thank you for your clarification, I now understand the issue.
